# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FinanceApp' do

  use_frameworks!

  # Pods for FinanceApp
  
  target 'FinanceAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SnapshotTesting'
  end

  target 'FinanceAppUITests' do
    # Pods for testing
  end

end
