# Uncomment the next line to define a global platform for your project
platform :ios, '15.2'

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

target 'FinanceApp' do
  use_frameworks!

  # Pods for FinanceApp

  target 'FinanceAppTests' do
    inherit! :search_paths
    pod 'SnapshotTesting', '~> 1.9.0'
  end

  target 'FinanceAppUITests' do
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.2'
    end
  end
end